# Generated by Django 3.0.3 on 2020-02-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200216_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polls',
            name='polls_1',
        ),
        migrations.RemoveField(
            model_name='polls',
            name='polls_2',
        ),
        migrations.CreateModel(
            name='Pollsmsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=20, verbose_name='内容')),
                ('coutmsg', models.FloatField(max_length=10, verbose_name='数量')),
                ('polls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Polls')),
            ],
        ),
    ]
