# Generated by Django 3.0.3 on 2020-02-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200216_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollsmsg',
            name='coutmsg',
            field=models.PositiveIntegerField(default=0, max_length=10, verbose_name='数量'),
        ),
    ]
